### ISSUE TITLE
feature request: list-all action

### ISSUE THREAD

**Issue by mathowie** [codeforamerica/glossary-bot#25]
I'd love it if there was a /gloss list-all feature that simply returned a comma delimited list of all defined words within glossary-bot.

**Comment by mathowie** [comment]
This would just be a tweak of the "learnings" command, just remove the date limit to get all records and order alphabetically.

**Comment by tmaybe** [comment]
hmm...there's an undocumented `random` modifier to the `learnings` command (i.e. `/gloss learnings random` gets you 12 random selections from the database); it'd be easy to add an `all` as well.

**Comment by tmaybe** [comment]
This is now available as of 6ec9f58e4e87dd3e31dada02afc35a388a65f330

You can now do the following:

* `/gloss learnings` for the default 12 most recently defined terms
* `/gloss learnings random` for a random 12 terms from the database
* `/gloss learnings all` to see all the terms at once.
* `/gloss learnings 50` to see the 50 most recent terms.
* `/gloss learnings 50 10` to see 50 terms, offset by 10 (so, terms 10-60)
* `/gloss learnings today` to see all the terms defined today
* `/gloss learnings yesterday` to see the terms defined yesterday

And you can combine parameters in ways that make sense.

You may have problems upgrading because I added a database migration earlier this week. Follow the instructions here:

https://github.com/codeforamerica/glossary-bot#upgrade-on-heroku

or get in touch if you have any problems.

**Comment by tmaybe** [comment]
Whoops, I missed that you asked for alphabetical sort. That's now in as of 600be51cc093d633df2d6d224bef80ae1248884b

Use it like so: `/gloss learnings alpha`
So `/gloss learnings all alpha` will get you all records ordered alphabetically.

**Comment by mathowie** [comment]
Thanks @tmaybe I got this all working for my team!

**Comment by migurski** [comment]
:fist: bump
